name: classic-gadget-kyle-1
version: 'classic-test-1'
type: gadget
summary: PC gadget for  classic
description: |
    This gadget enables generic pc devices to work with Ubuntu Core
grade: stable
confinement: strict
icon: icon.png

parts:
  hooks:
    plugin: dump
    source: hooks
    organize:
      prepare-device: snap/hooks/prepare-device

