#!/bin/sh
set -x

exec >> $SNAP_COMMON/prepare-device-hook.log 2>&1

# This will need hardware-observe interface
product_serial=test-kyle-serial-1

SERIAL_FILE=$SNAP_COMMON/test
echo "product_serial:[$product_serial]" > "$SERIAL_FILE"

if [ ! "$product_serial" ]; then
    echo "Empty product_serial"
    exit 1
fi

# Set the serial number of the device (needed for the serial assertion)
snapctl set registration.proposed-serial="'${product_serial}'"

# Set the location of the Serial Vault and the API key
snapctl set device-service.url="https://canonical.com/v1/"
snapctl set device-service.headers='{"api-key": "FkSfZTzAHH2b2z78U3S3ykjj2tcbe00xs6lp1NUDVfr4RbA3e1g"}'
